[package]
name = "kenr_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
tracing = "0.1.23"
tracing-subscriber = "0.3.9"
rusqlite = "0.27.0"
serenity = { version = "0.10.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }

[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]
